### ISSUE TITLE
Landing pages for events

### ISSUE THREAD

**Issue by jlooper** [VueVixens/website#1]
We need a landing page for each event. First is WeRiseConf.tech. It needs 2 buttons - I'm a Mentor, and I'm a Student, with 2 separate forms. Should we build the forms in Vue? Or use Google forms? Example: http://ng-girls.org/ngVikings/

**Comment by Gonzalo2310** [comment]
A standard landing page maybe?
Then adapted to each case.

**Comment by jlooper** [comment]
Completed, and much easier now that we have moved to TypeForms. So now, to create an event - 

create a typeform
find an image 
add it to CMS
