### ISSUE TITLE
Help a begginer to build and run your website

### ISSUE THREAD

**Issue by danrleywillyan** [VueVixens/website#33]
## Purpose
I am learning about vue.js and good practices to build websites using it, and I think that your site is awesome doing things like it do (in some parts is just the way that vue does things, it amazes me). I found your open code software and I am trying to build a development environmental and modify the software itself (the license say "You can modify").

## My Environmental 
OS: Debian 9
NPM: 6.4.1
node: 10.13.0

## Issue
I can build and run server, but I can't access routes. When I tried to access "/", "/Sponsors", "/Library", "/Gallery", "/Team" and "/About" that error happens.
![bugpart1](https://user-images.githubusercontent.com/12025215/48668809-5a646100-eadd-11e8-8065-a5b5f45be3bf.png)
![bugpart2](https://user-images.githubusercontent.com/12025215/48668755-761b3780-eadc-11e8-9d0f-f92a402bf319.png)

When I tried to access "/Request" and "/Credit" that error happens.
![bugpart4](https://user-images.githubusercontent.com/12025215/48668791-2d17b300-eadd-11e8-8832-027dc7013dff.png)

If anyone can help me, maybe it's a *obvious thing*; but to me it doesn't obvios.
# THANKS

**Comment by danrleywillyan** [comment]
I think it's happening because nuxt can't build routers correctly, i can't figure out why!

**Comment by danrleywillyan** [comment]
I change my OS and dev environmental to windows npm 5 and node 8; I understand that issue is caused because storyblok space that I changed to my own. In there has the websites' contents, how can I build it on my own space?

**Comment by danrleywillyan** [comment]
I want understand it. I want translate to Portuguese.

**Comment by NataliaTepluhina** [comment]
Can't say much about building it on Debian, don't have an environment to test.
Nuxt builds routes depending on what you have in your pages folder. If you don't have 'Request' page there, you will get 404

**Comment by danrleywillyan** [comment]
I understood I have to do a storyblock to website work correctly, but I didn't understand how set this. So I go on to another vue project. 
I aprecciate the answer.

**Comment by NataliaTepluhina** [comment]
You should create a new Storyblok space, set up your content and fetch this content in respective Vue components/views.
[Here](https://www.storyblok.com/tp/headless-cms-nuxtjs) you can find a tutorial that can help you to start with Nuxt +Storyblok
