### ISSUE TITLE
TODO - create blog link in navigation

### ISSUE THREAD

**Issue by jlooper** [VueVixens/website#36]
https://dev.to/vuevixens

Let's add this to the top nav, and link out.

**Comment by NataliaTepluhina** [comment]
@jlooper the link is added to the HomePage as a CTA. Do you want to replace CTA with Patreon one and move Blog to the Nav afterwards? I can join these 2 issues to 1 PR then

**Comment by jlooper** [comment]
Yes let’s add Patreon as the CTA and have the blog up top in Nav please
