### ISSUE TITLE
Rearrange Footer, move around Social Icons

### ISSUE THREAD

**Issue by jlooper** [VueVixens/website#40]
Let's make a few changes to our footer, here's what I suggest:

On the left side, let's have:

Press Kit (link to https://spark.adobe.com/page/FFczmvHR6Brpu/)
Credits
Contact Us (link to info@vuevixens.org)

On the right side, let's remove the social icons entirely.

I think we should have the GitHub icon in the top nav right before the translation buttons.
Then under the workshop and Patreon buttons, let's have newsletter, twitter, and slack icons, so we can get some more traffic to those areas.

**Comment by jlooper** [comment]
thank you @lauragift21 !! much appreciated

**Comment by NataliaTepluhina** [comment]
Resolved in #42
