### ISSUE TITLE
Edit shop link

### ISSUE THREAD

**Issue by jlooper** [VueVixens/website#73]
We are now forwarding vuevixens.com to our etsy shop, so please change the link in the top nav to vuevixens.com

**Comment by Manukam** [comment]
Hi, can I work on this?

**Comment by novellac** [comment]
Hi @Manukam! Thanks for checking it, but it looks like we have a PR for this functionality. Of course feel free to check back on this issue, or explore other issues on our board!

**Comment by MicheleCynowicz** [comment]
This is complete
