### ISSUE TITLE
Update Nuxt

### ISSUE THREAD

**Issue by novellac** [VueVixens/website#76]
**Task**
Update Nuxt and resolve any conflicts that arise.

**Comment by deepansh946** [comment]
@novellac I would like to work on this issue.

**Comment by novellac** [comment]
> @novellac I would like to work on this issue.

Hi @deepansh946  You are welcome to give it a try! Please ask questions here if you run into any issues, and we will do our best to help!

**Comment by KrzysztofKarol** [comment]
I'll try to do it as well.

**Comment by KrzysztofKarol** [comment]
It's done in https://github.com/VueVixens/website/pull/80.
I found that project uses both npm and yarn so I raised additional issue: https://github.com/VueVixens/website/issues/81.
